### ISSUE TITLE
error

### ISSUE THREAD

**Issue by Sagvi** [ntkhang03/fb-chat-api#1]
info login Logging in...
ERR! login Wrong username/password.
{ error: 'Wrong username/password.' }
i put good

**Comment by Sagvi** [comment]
on fb work

**Comment by ntkhang03** [comment]
because facebook changed "password" value in login api to "encpass" you need to use appstate. Utilities get appstate (here)[https://github.com/ntkhang03/c3c-fbstate/tree/add_new_feature]
