### ISSUE TITLE
Cannot login to Facebook

### ISSUE THREAD

**Issue by thecyberd3m0n** [ntkhang03/fb-chat-api#5]
using correct email + password, cannot login to Facebook (it seems like no redirection header is present and script says "Wrong username/password")

```
ERR! login Wrong username/password.
{ error: 'Wrong username/password.' }
```

**Comment by gushome7** [comment]
Same here. Ideas? Thanks

**Comment by miruchigawa** [comment]
Try using the cookie method. You can get the cookie by using a cookie editor, first log in to your Facebook account and then open the cookie editor and copy the cookie. The cookie editor can be found in the Chrome store

**Comment by ntkhang03** [comment]
Currently the function of login by email/password is no longer available. Please login using appState, here is the extension to get appState [click here](https://github.com/ntkhang03/c3c-fbstate)
