### ISSUE TITLE
ErrMarkAsDelivered

### ISSUE THREAD

**Issue by Hadestia** [ntkhang03/fb-chat-api#8]
Hi, this often happens after minutes or hour bot being active, it always throw this kind of error every seconds although my bot are not limited/muted by Facebook to any of thread. I hope this will be fixed, cuz it delays bot responses to any command and blocks my terminal and unable to debug anything. Thanks
![Screenshot_20230220-173448_1](https://user-images.githubusercontent.com/89353591/220068680-ce301e3a-7123-4d8a-8420-b07a9fe61027.png)

**Comment by ntkhang03** [comment]
Your Facebook account is indeed blocked, although you can use it normally, it has been blocked by Facebook on the hosting/device where you use this unofficial api. The only way is to wait they unblock or use proxies

**Comment by Hadestia** [comment]
I see, thanks
